### ISSUE TITLE
Compile C code with emit-llvm flag

### ISSUE THREAD

**Issue by slashmili** [wehlutyk/wasm-explorations#1]
Howdy!

I was trying to use  #3 example. The only way I managed to build it successfully was by adding `emit-llvm` flag

```diff
diff --git a/3-Rust+C-nostd/foo/Makefile b/3-Rust+C-nostd/foo/Makefile
index ac802a1..c0a6997 100644
--- a/3-Rust+C-nostd/foo/Makefile
+++ b/3-Rust+C-nostd/foo/Makefile
@@ -38,7 +38,7 @@ $(BAR_LIB_DIR)/libbar.a: $(BAR_LIB_DIR)/bar.o
        $(DOCKER_RUN) /clang/bin/llvm-ar rcsv $(BAR_LIB_DIR)/libbar.a $(BAR_LIB_DIR)/bar.o

 $(BAR_LIB_DIR)/bar.o: $(BAR_LIB_DIR)/bar.c
-       $(DOCKER_RUN) /clang/bin/clang -c --target=wasm32-unknown-unknown-wasm -o $(BAR_LIB_DIR)/bar.o $(BAR_LIB_DIR)/bar.c
+       $(DOCKER_RUN) /clang/bin/clang -c --target=wasm32-unknown-unknown-wasm -emit-llvm -o $(BAR_LIB_DIR)/bar.o $(BAR_LIB_DIR)/bar.c

 clean:
        cargo clean
```

Has something changed since you pushed this repo or I'm doing something wrong and this flag is not needed?

**Comment by wehlutyk** [comment]
Thanks for the report!

Indeed I haven't touched this in a while, and Rust's LLD must have been updated (since the Docker image hasn't changed, this must be it). After a bunch of updates I hit the same error, so thanks for the fix! (c8d910c2979eed80f4379aa2072ca10f408814ef)
